name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.13'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.13'
            tox_env: 'docs'
            os: 'ubuntu-latest'
          - name: 'py39 (ubuntu/x86_64)'
            artifact: 'py39-ubuntu-x86_64'
            python: '3.9'
            python_arch: 'x64'
            tox_env: 'py39'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py39 (windows/AMD64)'
            artifact: 'py39-windows-AMD64'
            python: '3.9'
            python_arch: 'x64'
            tox_env: 'py39'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py39 (macos/arm64)'
            artifact: 'py39-macos-arm64'
            python: '3.9'
            python_arch: 'arm64'
            tox_env: 'py39'
            cibw_arch: 'arm64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py310 (ubuntu/x86_64)'
            artifact: 'py310-ubuntu-x86_64'
            python: '3.10'
            python_arch: 'x64'
            tox_env: 'py310'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py310 (windows/AMD64)'
            artifact: 'py310-windows-AMD64'
            python: '3.10'
            python_arch: 'x64'
            tox_env: 'py310'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py310 (macos/arm64)'
            artifact: 'py310-macos-arm64'
            python: '3.10'
            python_arch: 'arm64'
            tox_env: 'py310'
            cibw_arch: 'arm64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py311 (ubuntu/x86_64)'
            artifact: 'py311-ubuntu-x86_64'
            python: '3.11'
            python_arch: 'x64'
            tox_env: 'py311'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py311 (windows/AMD64)'
            artifact: 'py311-windows-AMD64'
            python: '3.11'
            python_arch: 'x64'
            tox_env: 'py311'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py311 (macos/arm64)'
            artifact: 'py311-macos-arm64'
            python: '3.11'
            python_arch: 'arm64'
            tox_env: 'py311'
            cibw_arch: 'arm64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py312 (ubuntu/x86_64)'
            artifact: 'py312-ubuntu-x86_64'
            python: '3.12'
            python_arch: 'x64'
            tox_env: 'py312'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py312 (windows/AMD64)'
            artifact: 'py312-windows-AMD64'
            python: '3.12'
            python_arch: 'x64'
            tox_env: 'py312'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py312 (macos/arm64)'
            artifact: 'py312-macos-arm64'
            python: '3.12'
            python_arch: 'arm64'
            tox_env: 'py312'
            cibw_arch: 'arm64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py313 (ubuntu/x86_64)'
            artifact: 'py313-ubuntu-x86_64'
            python: '3.13'
            python_arch: 'x64'
            tox_env: 'py313'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py313 (windows/AMD64)'
            artifact: 'py313-windows-AMD64'
            python: '3.13'
            python_arch: 'x64'
            tox_env: 'py313'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py313 (macos/arm64)'
            artifact: 'py313-macos-arm64'
            python: '3.13'
            python_arch: 'arm64'
            tox_env: 'py313'
            cibw_arch: 'arm64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py314 (ubuntu/x86_64)'
            artifact: 'py314-ubuntu-x86_64'
            python: '3.14'
            python_arch: 'x64'
            tox_env: 'py314'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py314 (windows/AMD64)'
            artifact: 'py314-windows-AMD64'
            python: '3.14'
            python_arch: 'x64'
            tox_env: 'py314'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py314 (macos/arm64)'
            artifact: 'py314-macos-arm64'
            python: '3.14'
            python_arch: 'arm64'
            tox_env: 'py314'
            cibw_arch: 'arm64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py313t (ubuntu/x86_64)'
            artifact: 'py313t-ubuntu-x86_64'
            python: '3.13'
            python_arch: 'x64-freethreaded'
            tox_env: 'py313t'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py313t (windows/AMD64)'
            artifact: 'py313t-windows-AMD64'
            python: '3.13'
            python_arch: 'x64-freethreaded'
            tox_env: 'py313t'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py313t (macos/arm64)'
            artifact: 'py313t-macos-arm64'
            python: '3.13'
            python_arch: 'arm64-freethreaded'
            tox_env: 'py313t'
            cibw_arch: 'arm64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py314t (ubuntu/x86_64)'
            artifact: 'py314t-ubuntu-x86_64'
            python: '3.14'
            python_arch: 'x64-freethreaded'
            tox_env: 'py314t'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py314t (windows/AMD64)'
            artifact: 'py314t-windows-AMD64'
            python: '3.14'
            python_arch: 'x64-freethreaded'
            tox_env: 'py314t'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py314t (macos/arm64)'
            artifact: 'py314t-macos-arm64'
            python: '3.14'
            python_arch: 'arm64-freethreaded'
            tox_env: 'py314t'
            cibw_arch: 'arm64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'pypy39 (ubuntu/x86_64)'
            artifact: 'pypy39-ubuntu-x86_64'
            python: 'pypy-3.9'
            python_arch: 'x64'
            tox_env: 'pypy39'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'pypy39 (windows/AMD64)'
            artifact: 'pypy39-windows-AMD64'
            python: 'pypy-3.9'
            python_arch: 'x64'
            tox_env: 'pypy39'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'pypy39 (macos/arm64)'
            artifact: 'pypy39-macos-arm64'
            python: 'pypy-3.9'
            python_arch: 'arm64'
            tox_env: 'pypy39'
            cibw_arch: 'arm64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'pypy310 (ubuntu/x86_64)'
            artifact: 'pypy310-ubuntu-x86_64'
            python: 'pypy-3.10'
            python_arch: 'x64'
            tox_env: 'pypy310'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'pypy310 (windows/AMD64)'
            artifact: 'pypy310-windows-AMD64'
            python: 'pypy-3.10'
            python_arch: 'x64'
            tox_env: 'pypy310'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'pypy310 (macos/arm64)'
            artifact: 'pypy310-macos-arm64'
            python: 'pypy-3.10'
            python_arch: 'arm64'
            tox_env: 'pypy310'
            cibw_arch: 'arm64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'pypy311 (ubuntu/x86_64)'
            artifact: 'pypy311-ubuntu-x86_64'
            python: 'pypy-3.11'
            python_arch: 'x64'
            tox_env: 'pypy311'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'pypy311 (windows/AMD64)'
            artifact: 'pypy311-windows-AMD64'
            python: 'pypy-3.11'
            python_arch: 'x64'
            tox_env: 'pypy311'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'pypy311 (macos/arm64)'
            artifact: 'pypy311-macos-arm64'
            python: 'pypy-3.11'
            python_arch: 'arm64'
            tox_env: 'pypy311'
            cibw_arch: 'arm64'
            cibw_build: false
            os: 'macos-latest'
    steps:
    - uses: docker/setup-qemu-action@v3
      if: matrix.cibw_arch == 'aarch64'
      with:
        platforms: arm64
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off cibuildwheel -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: cibw build and test
      if: matrix.cibw_build
      run: cibuildwheel
      env:
        CIBW_ARCHS: '${{ matrix.cibw_arch }}'
        CIBW_BUILD: '${{ matrix.cibw_build }}'
        CIBW_CONTAINER_ENGINE: "docker; create_args: --cap-add=SYS_PTRACE"
        CIBW_ENABLE: cpython-freethreading
        CIBW_BUILD_VERBOSITY: '3'
        CIBW_TEST_REQUIRES: >
          tox
          tox-direct
        CIBW_TEST_COMMAND: >
          cd {project} &&
          tox --skip-pkg-install --direct-yolo -e ${{ matrix.tox_env }} -vv
        CIBW_TEST_COMMAND_WINDOWS: >
          cd /d {project} &&
          tox --skip-pkg-install --direct-yolo -e ${{ matrix.tox_env }} -vv
    - name: regular build and test
      if: >
        !matrix.cibw_build
      run: >
        tox -e ${{ matrix.tox_env }} -vv
    - name: check wheel
      if: >
        !matrix.cibw_ft && matrix.cibw_build
      run: |
        python -mpip install --progress-bar=off twine
        twine check wheelhouse/*.whl
    - name: upload wheel
      uses: actions/upload-artifact@v4
      if: matrix.cibw_build
      with:
        name: wheel-${{ matrix.artifact }}
        path: wheelhouse/*.whl
    - uses: coverallsapp/github-action@v2
      if: matrix.cover
      continue-on-error: true
      with:
        flag-name: ${{ matrix.name }}
        parallel: true
    - uses: codecov/codecov-action@v5
      if: matrix.cover
      with:
        flags: ${{ matrix.name }}
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact/merge@v4
      with:
        name: all-wheels
    - uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
